// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-layouts/Command.tsx": () => import("../components/mockups/home-layouts/Command.tsx"),
  "./components/mockups/home-layouts/Hero.tsx": () => import("../components/mockups/home-layouts/Hero.tsx"),
  "./components/mockups/home-layouts/Sidebar.tsx": () => import("../components/mockups/home-layouts/Sidebar.tsx")
};
